## Machine Learning Pipeline

As the class practice, the students will be required to develop a machine learning pipeline using the `Churn_Modelling_train_test.csv` dataset.

**About dataset**

This dataset is obained from [kaggle](https://www.kaggle.com/datasets/shubhammeshram579/bank-customer-churn-prediction?resource=download). It contains information on bank customers who either left the bank or continue to be a customer. The dataset includes the following attributes:

* Customer ID: A unique identifier for each customer
* Surname: The customer's surname or last name
* Credit Score: A numerical value representing the customer's credit score
* Geography: The country where the customer resides (France, Spain or Germany)
* Gender: The customer's gender (Male or Female)
* Age: The customer's age.
* Tenure: The number of years the customer has been with the bank
* Balance: The customer's account balance
* NumOfProducts: The number of bank products the customer uses (e.g., savings account, credit card)
* HasCrCard: Whether the customer has a credit card (1 = yes, 0 = no)
* IsActiveMember: Whether the customer is an active member (1 = yes, 0 = no)
* EstimatedSalary: The estimated salary of the customer
* Exited: Whether the customer has churned (1 = yes, 0 = no)

### Exploratory Data Analysis

In this section the students are required to do an EDA to understand the dataset.

In [1]:
# import packages
# import packages
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

import joblib
import os
import mlflow
import mlflow.sklearn

/Users/danielalbarrangonzalez/Documents/VSCode/mlops-and-system-design/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/danielalbarrangonzalez/Documents/VSCode/mlops-and-system-design/venv/lib/python3.9/site-packages/google/auth/__init__.py:54: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)
/Users/danielalbarrangonzalez/Documents/VSCode/mlops-and-system-design/venv/lib/python3.9/site-packages/google/oauth2/__init__.py:40: FutureWarning: You are using a Python version 3.9 past its end of life. Google will update google-auth with critical bug fixes on a best-effort basis, but not with any other fixes or features. Please upgrade your Python version, and then update google-auth.
  warnings.warn(eol_message.format("3.9"), FutureWarning)

In [6]:
df = pd.read_csv("../datasets/Churn_Modelling_train_test.csv")

df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,4784,15729224,Jennings,710,France,Female,37.0,5,0.00,2,1.0,0.0,115403.31,0
1,1497,15799156,Okwuadigbo,569,Spain,Male,38.0,8,0.00,2,0.0,0.0,79618.79,0
2,1958,15674922,Beavers,710,France,Male,54.0,6,171137.62,1,1.0,1.0,167023.95,1
3,9174,15653572,Thornton,673,Spain,Male,43.0,8,127132.96,1,0.0,1.0,6009.27,1
4,9748,15775761,Iweobiegbunam,610,Germany,Female,69.0,5,86038.21,3,0.0,0.0,192743.06,1

In [ ]:
# dataset analysis
# shape of dataset
print("Dataset shape:")
print(df.shape)

# column names
print("\nColumn names:")
print(df.columns)

# data types
print("\nData types:")
print(df.dtypes)

# missing values
print("\nMissing values:")
print(df.isnull().sum())

# statistical summary
print("\nStatistical summary:")
df.describe()

Dataset shape:
(9001, 14)

Column names:
Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

Data types:
RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                float64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard          float64
IsActiveMember     float64
EstimatedSalary    float64
Exited               int64
dtype: object

Missing values:
RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          1
Gender             0
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          1
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

Statistical summary:

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,9001.000000,9.001000e+03,9001.000000,9000.000000,9001.000000,9001.000000,9001.000000,9000.000000,9001.000000,9001.000000,9001.000000
mean,5003.366515,1.569072e+07,650.681369,38.901781,5.007888,76222.210827,1.531497,0.705667,0.514721,100180.823967,0.204422
std,2884.787499,7.179353e+04,96.539591,10.450760,2.894025,62432.198151,0.579398,0.455768,0.499811,57561.189534,0.403301
min,2.000000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.000000,0.000000,11.580000,0.000000
25%,2509.000000,1.562811e+07,584.000000,32.000000,2.000000,0.000000,1.000000,0.000000,0.000000,50972.600000,0.000000
50%,4989.000000,1.569096e+07,652.000000,37.000000,5.000000,96997.090000,1.000000,1.000000,1.000000,100556.980000,0.000000
75%,7505.000000,1.575265e+07,718.000000,44.000000,7.000000,127450.140000,2.000000,1.000000,1.000000,149458.730000,0.000000
max,10000.000000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.000000,1.000000,199992.480000,1.000000

In [9]:
# review categorical variables
print("\nCategorical variables:")
categorical_cols = df.select_dtypes(include=["object"]).columns
print(categorical_cols)

# review categorical variables

categorical_columns = ["Geography", "Gender"]

for col in categorical_columns:
    print(f"\nValue counts for {col}:")
    print(df[col].value_counts())

Categorical variables:
Index(['Surname', 'Geography', 'Gender'], dtype='object')

Value counts for Geography:
Geography
France     4505
Spain      2250
Germany    2245
Name: count, dtype: int64

Value counts for Gender:
Gender
Male      4906
Female    4095
Name: count, dtype: int64

In [11]:
# review binary variables
print("\nBinary variables:")
binary_cols = df.select_dtypes(include=["int64", "float64"]).columns
print(binary_cols)

# review binary variables

binary_columns = ["HasCrCard", "IsActiveMember", "Exited"]

for col in binary_columns:
    print(f"\nValue counts for {col}:")
    print(df[col].value_counts())

Binary variables:
Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

Value counts for HasCrCard:
HasCrCard
1.0    6351
0.0    2649
Name: count, dtype: int64

Value counts for IsActiveMember:
IsActiveMember
1.0    4633
0.0    4368
Name: count, dtype: int64

Value counts for Exited:
Exited
0    7161
1    1840
Name: count, dtype: int64

In [13]:
# review numerical variables
print("\nNumerical variables:")
numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns
print(numerical_cols)

# review numerical variables

numerical_columns = [
    "CreditScore",
    "Age",
    "Tenure",
    "Balance",
    "NumOfProducts",
    "EstimatedSalary"
]

df[numerical_columns].describe()

Numerical variables:
Index(['RowNumber', 'CustomerId', 'CreditScore', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
       'Exited'],
      dtype='object')

,CreditScore,Age,Tenure,Balance,NumOfProducts,EstimatedSalary
count,9001.000000,9000.000000,9001.000000,9001.000000,9001.000000,9001.000000
mean,650.681369,38.901781,5.007888,76222.210827,1.531497,100180.823967
std,96.539591,10.450760,2.894025,62432.198151,0.579398,57561.189534
min,350.000000,18.000000,0.000000,0.000000,1.000000,11.580000
25%,584.000000,32.000000,2.000000,0.000000,1.000000,50972.600000
50%,652.000000,37.000000,5.000000,96997.090000,1.000000,100556.980000
75%,718.000000,44.000000,7.000000,127450.140000,2.000000,149458.730000
max,850.000000,92.000000,10.000000,250898.090000,4.000000,199992.480000

**EDA Conclusions**

From this Exploratory Data Analysis we can retrieve the following information:
* *To be completed by the student*

Thankls to the Exploratory Data Analysis, we can conclude that the dataset contains more than 9,000 customer records with a combination of categorical, binary, and numerical variables and has no significant missing values. France represents approximately half of the customers, while Spain and Germany have a similar distribution. The dataset is also relatively balanced in terms of gender, with slightly more male customers than female. Anlayzing binary variables, we see that most customers own a credit card, and the number of active and inactive members is relatively similar. However, the target variable (Exited) is imbalanced, since the majority of customers did not leave the bank. Thanks to the numerical variables such as CreditScore, Age, Balance, and EstimatedSalary we can see that there´s good variability for model training. Additionally, some customers have zero balance while others maintain very large balances, which may become an important factor in predicting customer churn.

### ML Pipeline

In this section the students are required to create a ML pipeline to predict whether the customer left the bank or not.

In [14]:
# import packages
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

import joblib
import os

In [15]:
# Load the dataset
df = pd.read_csv("../datasets/Churn_Modelling_train_test.csv")

# preview dataset
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,4784,15729224,Jennings,710,France,Female,37.0,5,0.00,2,1.0,0.0,115403.31,0
1,1497,15799156,Okwuadigbo,569,Spain,Male,38.0,8,0.00,2,0.0,0.0,79618.79,0
2,1958,15674922,Beavers,710,France,Male,54.0,6,171137.62,1,1.0,1.0,167023.95,1
3,9174,15653572,Thornton,673,Spain,Male,43.0,8,127132.96,1,0.0,1.0,6009.27,1
4,9748,15775761,Iweobiegbunam,610,Germany,Female,69.0,5,86038.21,3,0.0,0.0,192743.06,1

In [17]:
# Preprocess the features - create a function or a class for it
def transform(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    df = df.drop(columns=["RowNumber", "CustomerId", "Surname"], errors="ignore")
    df = pd.get_dummies(df, columns=["Geography", "Gender"], drop_first=True)

    return df

In [18]:
# balance the dataset

df_transformed = transform(df)

# separate majority and minority classes
df_no_churn = df_transformed[df_transformed["Exited"] == 0]
df_churn = df_transformed[df_transformed["Exited"] == 1]

# downsample majority class
df_no_churn_sample = df_no_churn.sample(
    n=len(df_churn),
    random_state=42
)

# combine balanced dataset
df_balanced = pd.concat([df_no_churn_sample, df_churn])

# shuffle rows
df_balanced = df_balanced.sample(frac=1, random_state=42)

# review balance
df_balanced["Exited"].value_counts()

Exited
0    1840
1    1840
Name: count, dtype: int64

In [19]:
# Train a decision tree model using the `train sample`

# split features and target
X = df_balanced.drop("Exited", axis=1)
y = df_balanced["Exited"]

# train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# create model
model = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

# train model
model.fit(X_train, y_train)

print("Model trained successfully")

Model trained successfully

In [20]:
# Evaluate the performance in the test sample

# predictions
y_pred = model.predict(X_test)

# metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

# print metrics
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

# confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.7391304347826086
Precision: 0.7549295774647887
Recall: 0.7184986595174263
F1 Score: 0.7362637362637363

Confusion Matrix:
[[276  87]
 [105 268]]

### MLFlow Integration

In this section the students are required to track the model and the parameters into MLFlow.

In [21]:
# import packages for mlfow
import mlflow

Start a local Tracking server on port 8080 - it is necessary to import mlflow and open a new terminal

In [22]:
# Set our tracking server uri for logging on port 8080
mlflow.set_tracking_uri("http://127.0.0.1:8080")

Visit the MLFlow UI on `http://127.0.0.1:8080`

In [23]:
# Create a new MLflow Experiment
mlflow.set_experiment("Practice Experiment - Daniel")

2026/05/14 20:17:35 INFO mlflow.tracking.fluent: Experiment with name 'Practice Experiment - Daniel' does not exist. Creating a new experiment.

<Experiment: artifact_location='mlflow-artifacts:/504873828879810771', creation_time=1778782655528, experiment_id='504873828879810771', last_update_time=1778782655528, lifecycle_stage='active', name='Practice Experiment - Daniel', tags={}>

In [24]:
# Start an MLflow run

with mlflow.start_run():

    # Log the hyperparameters
    mlflow.log_param("model_type", "DecisionTree")
    mlflow.log_param("max_depth", 5)
    mlflow.log_param("test_size", 0.2)

    # Log the metrics
    mlflow.log_metric("accuracy", accuracy)
    mlflow.log_metric("precision", precision)
    mlflow.log_metric("recall", recall)
    mlflow.log_metric("f1_score", f1)

    # Set tags
    mlflow.set_tag("project", "Customer Churn Prediction")
    mlflow.set_tag("author", "Daniel")

    # Log the model
    mlflow.sklearn.log_model(
        sk_model=model,
        artifact_path="decision_tree_model"
    )

    print("MLflow run completed successfully")

2026/05/14 20:21:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

MLflow run completed successfully
🏃 View run amazing-yak-249 at: http://127.0.0.1:8080/#/experiments/504873828879810771/runs/6b9bb8e6aa4044d88d03f0d8d4b3dcb2
🧪 View experiment at: http://127.0.0.1:8080/#/experiments/504873828879810771

### Keep practicing

In [3]:
# Create a new experiment using other models or different parameters
...